/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SystemDescriptorUiModule extends AbstractSystemDescriptorUiModule {

	public SystemDescriptorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
