/**
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.tests;

import com.google.inject.Inject;
import com.ngc.seaside.systemdescriptor.systemDescriptor.Model;
import com.ngc.seaside.systemdescriptor.tests.SystemDescriptorInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.junit4.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(SystemDescriptorInjectorProvider.class)
@SuppressWarnings("all")
public class JsonParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  @Inject
  private ValidationTestHelper validationTester;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("metadata {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("\"name\" : \"test\",");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("\"description\" : \"A test metadata object\",");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("\"alias\" : [\"metadata\", \"test\"]");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Model result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      this.validationTester.assertNoIssues(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
