/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SystemDescriptorStandaloneSetup extends SystemDescriptorStandaloneSetupGenerated {

	def static void doSetup() {
		new SystemDescriptorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
