/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor

import com.google.inject.Binder

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SystemDescriptorRuntimeModule extends AbstractSystemDescriptorRuntimeModule {

	override public void configure(Binder binder) {
		super.configure(binder)
	}
}
