/**
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.validation;

import com.ngc.seaside.systemdescriptor.validation.AbstractSystemDescriptorValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SystemDescriptorValidator extends AbstractSystemDescriptorValidator {
}
