/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.ui.tests;

import com.google.inject.Injector;
import com.ngc.seaside.systemdescriptor.ui.internal.SystemdescriptorActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class SystemDescriptorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SystemdescriptorActivator.getInstance().getInjector("com.ngc.seaside.systemdescriptor.SystemDescriptor");
	}

}
