/**
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor;

import com.ngc.seaside.systemdescriptor.AbstractSystemDescriptorRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SystemDescriptorRuntimeModule extends AbstractSystemDescriptorRuntimeModule {
}
