/**
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SystemDescriptorStandaloneSetup /* implements SystemDescriptorStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type SystemDescriptorStandaloneSetup");
  }
}
