/**
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor;

import com.ngc.seaside.systemdescriptor.SystemDescriptorStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SystemDescriptorStandaloneSetup extends SystemDescriptorStandaloneSetupGenerated {
  public static void doSetup() {
    SystemDescriptorStandaloneSetup _systemDescriptorStandaloneSetup = new SystemDescriptorStandaloneSetup();
    _systemDescriptorStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
