/**
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.systemDescriptor;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ngc.seaside.systemdescriptor.systemDescriptor.SystemDescriptorPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends Element
{
} // Model
