/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSystemDescriptorScopeProvider extends DelegatingScopeProvider {
}
