/**
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.ui;

import com.ngc.seaside.systemdescriptor.ui.AbstractSystemDescriptorUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SystemDescriptorUiModule extends AbstractSystemDescriptorUiModule {
  public SystemDescriptorUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
