/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import com.ngc.seaside.systemdescriptor.systemDescriptor.Descriptor

@RunWith(XtextRunner)
@InjectWith(SystemDescriptorInjectorProvider)
class JsonParsingTest {

	@Inject
	ParseHelper<Descriptor> parseHelper
	
	@Inject
    ValidationTestHelper validationTester

	@Test 
	def void testDoesParseMetadataAsJson() {
		val result = parseHelper.parse('''
			package blah
			
			data Foo { 
				metadata {
				  "name" : "test",
				  "description" : "A test metadata object",
				  "alias" : ["metadata", "test"]
				}  
			}
		''')
		Assert.assertNotNull(result)
		validationTester.assertNoIssues(result);
	}

}
