/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.tests

import com.google.inject.Inject
import com.ngc.seaside.systemdescriptor.systemDescriptor.Model
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.junit4.validation.ValidationTestHelper

@RunWith(XtextRunner)
@InjectWith(SystemDescriptorInjectorProvider)
class SystemDescriptorParsingTest{

	@Inject
	ParseHelper<Model> parseHelper
	
	@Inject
    ValidationTestHelper validationTester

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			metadata {
				"name" : "test",
				"description" : "A test metadata object",
				"alias" : ["metadata", "test"]
			}
		''')
		Assert.assertNotNull(result)
		validationTester.assertNoIssues(result);
	}

}
