/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.tests

import com.google.inject.Inject
import com.ngc.seaside.systemdescriptor.systemDescriptor.Package
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

import static org.junit.Assert.*
import com.ngc.seaside.systemdescriptor.systemDescriptor.ArrayValue
import com.ngc.seaside.systemdescriptor.systemDescriptor.StringValue

@RunWith(XtextRunner)
@InjectWith(SystemDescriptorInjectorProvider)
class JsonParsingTest {

	@Inject
	ParseHelper<Package> parseHelper

	@Inject
	ValidationTestHelper validationTester

	@Test
	def void testDoesParseMetadataAsJson() {
		val result = parseHelper.parse('''
			package blah
			
			data Foo { 
				metadata {
				  "name" : "test",
				  "description" : "A test metadata object",
				  "arraydata" : ["metadata", "test"],
				  "boolvalue" : true
				}  
			}
		''')
		Assert.assertNotNull(result)
		validationTester.assertNoIssues(result);
		
		// get the array data
		var metadata = result.element.metadata
		val arraymember = metadata.json.members.get(2)
		assertEquals(
			"metadata did not parse!",
			"arraydata",
			arraymember.key
		)
		
		var arrayvalue = (arraymember.value as ArrayValue).value
		assertEquals(
			"metadata did not parse!",
			2,
			arrayvalue.values.size()
		)	
		assertEquals(
			"metadata did not parse!",
			"metadata",
			(arrayvalue.values.get(0) as StringValue).value
		)	
		assertEquals(
			"metadata did not parse!",
			"test",
			(arrayvalue.values.get(1) as StringValue).value
		)			
	}

}
