/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SystemDescriptorAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/ngc/seaside/systemdescriptor/parser/antlr/internal/InternalSystemDescriptor.tokens");
	}
}
