/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.parser.antlr;

import com.google.inject.Inject;
import com.ngc.seaside.systemdescriptor.parser.antlr.internal.InternalSystemDescriptorParser;
import com.ngc.seaside.systemdescriptor.services.SystemDescriptorGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SystemDescriptorParser extends AbstractAntlrParser {

	@Inject
	private SystemDescriptorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSystemDescriptorParser createParser(XtextTokenStream stream) {
		return new InternalSystemDescriptorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Descriptor";
	}

	public SystemDescriptorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SystemDescriptorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
