/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.ui;

import com.google.inject.Injector;
import com.ngc.seaside.systemdescriptor.ui.internal.SystemdescriptorActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SystemDescriptorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SystemdescriptorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SystemdescriptorActivator.getInstance().getInjector(SystemdescriptorActivator.COM_NGC_SEASIDE_SYSTEMDESCRIPTOR_SYSTEMDESCRIPTOR);
	}
	
}
