/*
 * generated by Xtext 2.10.0
 */
package com.ngc.seaside.systemdescriptor.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
public class SystemDescriptorOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
