/*
 * generated by Xtext 2.12.0
 */
package com.ngc.seaside.systemdescriptor.ide


/**
 * Use this class to register ide components.
 */
class SystemDescriptorIdeModule extends AbstractSystemDescriptorIdeModule {
}
